/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/jobs/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job */
        post: operations["create_job_api_v1_jobs_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Results */
        get: operations["get_job_results_api_v1_jobs__job_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Status */
        get: operations["get_job_status_api_v1_jobs__job_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BriefFields */
        BriefFields: {
            /**
             * Desired Functions
             * @description Desired functions of the therapeutic product
             */
            desired_functions: ("angiogenesis" | "anti_inflammatory" | "antimicrobial" | "cell_proliferation/migration" | "collagen_remodeling" | "collagen_synthesis" | "fibroblast_migration" | "immunomodulation" | "keratinocyte_migration")[];
            /** Dosing Interval Hours */
            dosing_interval_hours: number;
            /** Max Length */
            max_length: number;
            /** Min Length */
            min_length: number;
            /** Pathogens */
            pathogens: ("Escherichia_coli" | "Staphylococcus_aureus" | "Pseudomonas_aeruginosa")[];
            /**
             * Wound Context
             * @description Context of the wound
             */
            wound_context: ("acute" | "biofilm_positive" | "burn" | "chronic" | "clean" | "diabetic" | "high_exudate" | "high_glucose" | "infected" | "ischemic" | "low_perfusion" | "necrotic" | "radiation_induced" | "surgical" | "traumatic")[];
        };
        /** CandidateResponse */
        CandidateResponse: {
            /** Aggregation Tendency */
            aggregation_tendency?: number | null;
            /** Amp Probability */
            amp_probability?: number | null;
            /** Angiogenic Activity */
            angiogenic_activity?: number | null;
            /** Anti Inflammatory Probability */
            anti_inflammatory_probability?: number | null;
            /** Cleavage Stability */
            cleavage_stability?: number | null;
            /** Cytotoxicity Probability */
            cytotoxicity_probability?: number | null;
            /** Deamidation Risk */
            deamidation_risk?: ("low" | "medium" | "high") | null;
            /** Engaged Pathways */
            engaged_pathways?: string[] | null;
            /** Hemolytic Activity Phc50 */
            hemolytic_activity_phc50?: number | null;
            /**
             * Id
             * @default ?
             */
            id: string;
            /** Instability Index */
            instability_index?: number | null;
            /** Log Mic Um */
            log_mic_um: {
                [key: string]: number;
            };
            /**
             * Migration Probability
             * @default 0
             */
            migration_probability: number | null;
            /** Molecular Weight */
            molecular_weight?: number | null;
            /** Net Charge */
            net_charge?: number | null;
            /** Oxidation Risk */
            oxidation_risk?: ("low" | "medium" | "high") | null;
            /** Pmbic */
            pmbic: {
                [key: string]: number;
            };
            /**
             * Proliferation Probability
             * @default 0
             */
            proliferation_probability: number | null;
            /** Ranking */
            ranking?: number | null;
            /** Sequence */
            sequence?: string | null;
            /** Solubility */
            solubility?: number | null;
        };
        /** ComponentStats */
        ComponentStats: {
            /** Count */
            count: number;
            /** Max */
            max: number;
            /** Mean */
            mean: number;
            /** Median */
            median: number;
            /** Min */
            min: number;
        };
        /** CreateJobRequest */
        CreateJobRequest: {
            /** Request Id */
            request_id: string;
            stages: components["schemas"]["E2ERequest"];
        };
        /** CreateJobResponse */
        CreateJobResponse: {
            /** Job Id */
            job_id: string;
            /** Request Id */
            request_id: string;
            /** Result Path */
            result_path: string;
        };
        /**
         * E2ERequest
         * @description The public e2e job request shape: one field per client-configurable
         *     stage, each stage's own params flattened together with its `enabled`
         *     flag (no {"params": {...}} wrapper). Every field is required to be
         *     present (a bare {} accepts that stage's defaults) so the OpenAPI schema
         *     and pydantic validation reflect the real per-stage shape directly,
         *     instead of a generic dict a stage name could otherwise be mismatched
         *     against. s02_wound_biology_and_targets, s03_data_integration, and
         *     s11_ranking are deliberately absent -- e2e_config.py always overrides
         *     them itself (s02/s03 force-disabled, s11 force-default), so nothing a
         *     client sends for them would ever be used.
         */
        E2ERequest: {
            s01_therapeutic_product_brief: components["schemas"]["Stage1Request"];
            s04_candidate_generation: components["schemas"]["Stage4Request"];
            s05_physchem_screening: components["schemas"]["Stage5Request"];
            s06_functional_models: components["schemas"]["Stage6Request"];
            s07_structure_mechanism: components["schemas"]["Stage7Request"];
            s08_safety_developability: components["schemas"]["Stage8Request"];
            s09_synthesis_cmc: components["schemas"]["Stage9Request"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobResultsResponse */
        JobResultsResponse: {
            /**
             * Candidates
             * @default []
             */
            candidates: components["schemas"]["CandidateResponse"][];
            /** Component Stats */
            component_stats?: {
                [key: string]: components["schemas"]["ComponentStats"];
            };
            /** Insufficient Evidence Candidates */
            insufficient_evidence_candidates?: number | null;
            /** Job Id */
            job_id: string;
            /** N Final */
            n_final?: number | null;
            /** Ranked Candidates */
            ranked_candidates?: number | null;
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
        };
        /** JobStatusResponse */
        JobStatusResponse: {
            /** Error */
            error?: string | null;
            /** Job Id */
            job_id: string;
            /**
             * Stage
             * @default pending
             */
            stage: string | null;
            /** Status */
            status: string;
            /** Vertex State */
            vertex_state: string;
        };
        /** RouteAConstraintConfig */
        RouteAConstraintConfig: {
            /**
             * Aggregation Threshold
             * @default 3
             */
            aggregation_threshold: number;
            /**
             * Charge Max
             * @default 8
             */
            charge_max: number;
            /**
             * Charge Min
             * @default -3
             */
            charge_min: number;
            /**
             * Hydro Max
             * @default 1
             */
            hydro_max: number;
            /**
             * Hydro Min
             * @default -1
             */
            hydro_min: number;
            /**
             * Ph
             * @default 7.4
             */
            ph: number;
        };
        /** RouteAGAParams */
        RouteAGAParams: {
            /**
             * Mutation Rate
             * @default 0.1
             */
            mutation_rate: number;
            /**
             * N Generations
             * @default 5
             */
            n_generations: number;
            /**
             * Pop Size
             * @default 3
             */
            pop_size: number;
            /**
             * Random Seed
             * @default 42
             */
            random_seed: number;
        };
        /** Stage1Request */
        Stage1Request: {
            brief: components["schemas"]["BriefFields"];
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Seed
             * @description Random seed for reproducibility
             * @default 42
             */
            seed: number;
        };
        /** Stage4Request */
        Stage4Request: {
            /**
             * Batch Size
             * @default 16
             */
            batch_size: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Generator */
            generator?: string | null;
            /**
             * Max Attempts
             * @default 20
             */
            max_attempts: number;
            /**
             * Max New Tokens
             * @default 120
             */
            max_new_tokens: number;
            /**
             * N Peptides
             * @default 100
             */
            n_peptides: number;
            /**
             * @default {
             *       "aggregation_threshold": 3,
             *       "charge_max": 8,
             *       "charge_min": -3,
             *       "hydro_max": 1,
             *       "hydro_min": -1,
             *       "ph": 7.4
             *     }
             */
            route_a_constraint_config: components["schemas"]["RouteAConstraintConfig"];
            /**
             * @default {
             *       "mutation_rate": 0.1,
             *       "n_generations": 5,
             *       "pop_size": 3,
             *       "random_seed": 42
             *     }
             */
            route_a_ga_params: components["schemas"]["RouteAGAParams"];
            /**
             * Tags
             * @default [
             *       "<AMP>"
             *     ]
             */
            tags: ("<AMP>" | "<ANTIBIOFILM>" | "<ANTIBACTERIAL>")[];
        };
        /** Stage5Request */
        Stage5Request: {
            /**
             * Aggregation Tendency Flag Max
             * @default 0.6
             */
            aggregation_tendency_flag_max: number;
            /**
             * Amphipathicity Flag Max
             * @default 0.8
             */
            amphipathicity_flag_max: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Isoelectric Point Flag Ph Window
             * @default 0.5
             */
            isoelectric_point_flag_ph_window: number;
            /**
             * Ph
             * @default 7.4
             */
            ph: number;
            /**
             * Risk Category Low Max
             * @default 0
             */
            risk_category_low_max: number;
            /**
             * Risk Category Medium Max
             * @default 2
             */
            risk_category_medium_max: number;
            /**
             * Solubility Flag Min
             * @default 0.4
             */
            solubility_flag_min: number;
            /**
             * Solubility Solvent
             * @default Ultrapure water
             */
            solubility_solvent: string;
            /**
             * Ss Confidence Ambiguous Max
             * @default 0.7
             */
            ss_confidence_ambiguous_max: number;
            /**
             * Ss Confidence Unstable Max
             * @default 0.5
             */
            ss_confidence_unstable_max: number;
        };
        /** Stage6Request */
        Stage6Request: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * @default {
             *       "max_mbic": {
             *         "Candida_albicans": 32,
             *         "Pseudomonas_aeruginosa": 32,
             *         "Staphylococcus_aureus": 32
             *       },
             *       "max_mic": {
             *         "Escherichia_coli": 32,
             *         "Pseudomonas_aeruginosa": 32,
             *         "Staphylococcus_aureus": 32
             *       },
             *       "min_amp_probability": 0.7,
             *       "min_angiogenic_activity": 0.1,
             *       "min_anti_inflammatory_probability": 0.5,
             *       "min_proliferation_migration": 0.5
             *     }
             */
            stage6_thresholds: components["schemas"]["Stage6Thresholds"];
        };
        /** Stage6Thresholds */
        Stage6Thresholds: {
            /**
             * Max Mbic
             * @default {
             *       "Candida_albicans": 32,
             *       "Pseudomonas_aeruginosa": 32,
             *       "Staphylococcus_aureus": 32
             *     }
             */
            max_mbic: {
                [key: string]: number;
            };
            /**
             * Max Mic
             * @default {
             *       "Escherichia_coli": 32,
             *       "Pseudomonas_aeruginosa": 32,
             *       "Staphylococcus_aureus": 32
             *     }
             */
            max_mic: {
                [key: string]: number;
            };
            /**
             * Min Amp Probability
             * @default 0.7
             */
            min_amp_probability: number;
            /**
             * Min Angiogenic Activity
             * @default 0.1
             */
            min_angiogenic_activity: number;
            /**
             * Min Anti Inflammatory Probability
             * @default 0.5
             */
            min_anti_inflammatory_probability: number;
            /**
             * Min Proliferation Migration
             * @default 0.5
             */
            min_proliferation_migration: number;
        };
        /** Stage7Request */
        Stage7Request: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Helix Phi Max
             * @default -30
             */
            helix_phi_max: number;
            /**
             * Helix Phi Min
             * @default -100
             */
            helix_phi_min: number;
            /**
             * Helix Psi Max
             * @default -5
             */
            helix_psi_max: number;
            /**
             * Helix Psi Min
             * @default -77
             */
            helix_psi_min: number;
            /**
             * Pathway Engagement Min Probability
             * @default 0.5
             */
            pathway_engagement_min_probability: number;
            /**
             * Plddt Low Confidence Max
             * @default 0.5
             */
            plddt_low_confidence_max: number;
            /**
             * Sheet Phi Max
             * @default -45
             */
            sheet_phi_max: number;
            /**
             * Sheet Phi Min
             * @default -180
             */
            sheet_phi_min: number;
            /**
             * Sheet Psi Max
             * @default 180
             */
            sheet_psi_max: number;
            /**
             * Sheet Psi Min
             * @default 90
             */
            sheet_psi_min: number;
        };
        /** Stage8Request */
        Stage8Request: {
            /**
             * Aggregation Reject Max
             * @default 0.7
             */
            aggregation_reject_max: number;
            /**
             * Cleavage Decay Rate
             * @default 0.5
             */
            cleavage_decay_rate: number;
            /**
             * Cleavage Stability Reject Min
             * @default 0.3
             */
            cleavage_stability_reject_min: number;
            /**
             * Cytotoxicity Cell Type
             * @default DRAMP_aggregate
             * @enum {string}
             */
            cytotoxicity_cell_type: "DBAASP_no_cytotoxicity_hit" | "DRAMP_aggregate" | "Human PBMC" | "Human Primary Epidermal Keratinocytes (HEK)" | "Human keratinocytes HaCat" | "Human microvascular endothelial cells HMEC-1" | "Human skin fibroblasts";
            /**
             * Cytotoxicity Reject Max
             * @default 0.5
             */
            cytotoxicity_reject_max: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Hemolysis Phc50 Reject Max
             * @default 4
             */
            hemolysis_phc50_reject_max: number;
            /**
             * Solubility Flag Min
             * @default 0.3
             */
            solubility_flag_min: number;
            /**
             * Solubility Solvent
             * @default Ultrapure water
             */
            solubility_solvent: string;
        };
        /** Stage9Request */
        Stage9Request: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Rejected Difficulty Classes
             * @default [
             *       "high"
             *     ]
             */
            rejected_difficulty_classes: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_job_api_v1_jobs_create_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_results_api_v1_jobs__job_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResultsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_status_api_v1_jobs__job_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
